version: 0.0
os: linux
files:
  - source: "/"
    destination: "/var/www/cookie-numerique"
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: "ci-cd/before-install.sh"
      timeout: 3000
      runas: ubuntu
  Install:
    - location: "ci-cd/install.sh"
      timeout: 60
      runas: ubuntu
  AfterInstall:
    - location: "ci-cd/after-install.sh"
      timeout: 10
      runas: ubuntu